version: 0.1

services:
  db:
    image: postgres
    env_file:
      - .env
  web:
    pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
    build: .
    commands: 
      - bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      - echo Building the application 


    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

artifacts:
  files:
    - '**/*'
  name: build-artifact-name
  discard-paths: no      


