# Generated by Django 4.0.1 on 2023-08-16 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empresa', models.CharField(max_length=2)),
                ('cod_producto', models.CharField(max_length=100)),
                ('cod_proveedor', models.CharField(blank=True, max_length=11, null=True)),
                ('cod_unidad_medida', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_tipo_producto', models.IntegerField()),
                ('cod_garantia', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_linea_producto', models.CharField(max_length=5)),
                ('cod_categoria', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_marca', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_presentacion', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_procedencia', models.CharField(blank=True, max_length=3, null=True)),
                ('des_producto', models.CharField(max_length=255)),
                ('des_adicional', models.TextField(blank=True, null=True)),
                ('des_tecnicas', models.TextField(blank=True, null=True)),
                ('des_info_adicional', models.TextField(blank=True, null=True)),
                ('num_parte', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_barra', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_registro', models.DateField()),
                ('stk_minimo', models.FloatField()),
                ('stk_proveedor', models.FloatField()),
                ('pre_costo_promedio_anterior', models.FloatField()),
                ('pre_costo_promedio', models.FloatField()),
                ('pre_compra_base', models.FloatField()),
                ('pre_venta_base_anterior', models.FloatField()),
                ('pre_venta_base', models.FloatField()),
                ('pre_unitario_base_anterior', models.FloatField()),
                ('pre_unitario_base', models.FloatField()),
                ('pre_venta_oferta', models.FloatField()),
                ('pre_unitario_oferta', models.FloatField()),
                ('des_web_referencial', models.CharField(max_length=255)),
                ('ind_servicio', models.CharField(max_length=1)),
                ('ind_autogenerado', models.CharField(max_length=1)),
                ('ind_lote_serie1', models.CharField(max_length=1)),
                ('ind_activo_web', models.CharField(max_length=1)),
                ('ind_mostrar_portal', models.CharField(max_length=1)),
                ('ind_catalogo', models.CharField(max_length=1)),
                ('ind_lote', models.CharField(max_length=1)),
                ('ind_importado', models.CharField(max_length=1)),
                ('ind_activo', models.CharField(max_length=1)),
                ('code_user_insert', models.CharField(max_length=10)),
                ('date_insert', models.DateField(blank=True, null=True)),
                ('code_user_last_update', models.CharField(blank=True, max_length=10, null=True)),
                ('date_last_update', models.DateField(blank=True, null=True)),
                ('ind_serie', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_ide', models.CharField(max_length=20, unique=True)),
                ('correo', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
